### ISSUE TITLE
[FEATURE] [Migrated] Cooldown on chopping down a tree

### ISSUE THREAD

**Issue by PierreSchwang** [SourceWriters/SmoothTimber#1]
Implement a cooldown in seconds when chopping down a tree. The amount of seconds a player has to wait before they can chop a tree again.
Also a bypass permission for no cooldown.

Migrated from GitLab issue: https://gitlab.com/SyntaxPhoenix/SmoothTimber/-/issues/32

**Comment by Lauriichan** [comment]
Was added in bff656e1cd9176ef7a969db7414b9193bb8d33b5
