### ISSUE TITLE
[BUG] Unable to destroy log block with cutter enabled

### ISSUE THREAD

**Issue by mari-arondeus** [SourceWriters/SmoothTimber#11]
**Describe the bug**
Cutter aborts without error. No log lines are generated (even with debug mode on), and no message is sent to the player. Toggling the cutter off allows for normal destruction. CoreProtect does not log a block destruction event.

**To Reproduce**
1. Install the SmoothTimber plugin.
2. Equip an axe of any material and attempt to break the bottom block of a world-generated tree.

**Expected behavior**
The tree should be destroyed as expected.

**Media**
No animation is played. The block pops back instantly and does not appear to be destroyed to other players.

**Server**
 - Software: Paper r778
 - Server Version: Minecraft 1.16.5
 - Plugin Version: SmoothTimber 1.16.5
 - Java Version: OpenJDK 16.0.1+9

**Additional context**
@LENTIS80#7453 in the Discord support channel appears to be having the same issue. 
I'm happy to provide a list of in-use plugins if needed.

**Comment by Lauriichan** [comment]
Could send us your config file?

**Comment by mari-arondeus** [comment]
[As requested.](https://gist.github.com/cassidy3/950aa7e57c23d06ef8f542b0694cf552) Here's the [addons config](https://gist.github.com/cassidy3/a6b90434a5bd56961fe69ac09155d832) and the [list of installed plugins](https://gist.github.com/cassidy3/4ace5f306d5416bc1809ae2669eed0a2) for good measure.

**Comment by Lauriichan** [comment]
Did u sneak while breaking the block?
As your plugin is configured to only trigger on sneak

**Comment by mari-arondeus** [comment]
Yes. That was configured *after* noticing the issue to avoid preventing players from being unable to break trees. Sneaking/cutter enabled ==> cannot break the log. Not sneaking/cutter disabled ==> can break the log, but the tree does not fall.

Edit: I assume it goes without saying that the behavior was inverted before I changed that config line.

**Comment by Lauriichan** [comment]
Okay so small recap: Trees are not falling at all when using SmoothTimber?

**Comment by mari-arondeus** [comment]
Correct. In any situation in which the SmoothTimber cutter tool _should_ be felling trees, it is not. It simply does not destroy the log we attempt to chop.

**Comment by Lauriichan** [comment]
Okay did u already try to use the latest SmoothTimber version?
As the older ones probably doesn't really work on Java 16

**Comment by mari-arondeus** [comment]
I used version 1.16.5 - I assumed later version were for more recent versions of the game. Would SmoothTimber v1.17.1 be compatible with Minecraft 1.16.5? I'm happy to test it out if that's the case.

**Comment by Lauriichan** [comment]
As I said, try to use the latest version.
SmoothTimber is always compatible with all versions from 1.8 to latest

**Comment by mari-arondeus** [comment]
Ahh, I see. I misunderstood the version numbering - I assumed it referred to game version. Anyway, I just tried with SmoothTimber 1.17.1 and saw the exact same issue. Still not log lines unfortunately.

**Comment by Lauriichan** [comment]
No it doesn't refer to the game version and okay I'll look into that soon

**Comment by mari-arondeus** [comment]
Thank you!! And no rush of course; it only appears to affect a few people and admittedly there's not much debugging information to provide. Just wanted to make sure it's on your radar.

Edit: bumped to MC version 1.17.1, plugin version 1.17.3. Issue still present.

**Comment by Lauriichan** [comment]
Okay
The plugins are still the same I guess, so it might be an issue with CoreProtect, one thing could you try to disable CoreProtect in the addons.yml (you dont need to restart the server or anything)

Edit: And sorry for the late answer I completly forgot to check my github >.<

**Comment by Lauriichan** [comment]
So after a bit of testing with CoreProtect and SmoothTimber (on 1.16.5 MC / 1.17.3 ST / 19.5 CP / Java 16)
I got no problems at all, everything works flawlessly.
I exactly copied your config tried naturally generated trees as well as planted ones

Edit: For now I'll mark this issue as invalid but I'll leave it open

**Comment by mari-arondeus** [comment]
Understandable. Is there any way more verbose debug logging could be added in the future to make this sort of issue easier to diagnose? I get that plugin conflicts are often going to make debugging very difficult but having zero log lines whatsoever makes it impossible to even know where to start :(

**Comment by Lauriichan** [comment]
That could be a good idea for SmoothTimber version 2

**Comment by Lauriichan** [comment]
> Understandable. Is there any way more verbose debug logging could be added in the future to make this sort of issue easier to diagnose? I get that plugin conflicts are often going to make debugging very difficult but having zero log lines whatsoever makes it impossible to even know where to start :(

Hey there,
I just revisited this issue (just here on github)
And I think the problem could be that you're using MySQL with CoreProtect
I remembered that someone had a problem already with CoreProtect when using MySQL with it as it is really slow doing its requests to the MySQL and SmoothTimber only waits a specific amount of time per request.
Therefore SmoothTimber probably skips the blocks and therefore doesn't break them.

(At least that's the only thing I can imagine of being a problem)

**Comment by mari-arondeus** [comment]
You know, that actually makes a lot of sense! The DB it's hitting has a pretty slow response time (which is fine for CoreProtect and the other plugins we have installed, at least on a small scale), so I can see how that would happen. Is there any way SmoothTimber could log this kind of behavior, maybe locked behind a debug config option? Even if it isn't clear as to what the reason is, just having a "Error: SmoothTimber has timed out (xx.xxms)" would go a long way to save troubleshooting headaches in the future. I'm sure this isn't the last time this kind of issue will pop up.

Anyways, thank you for staying on top of this. I'll do some testing of my own and see if reducing network latency between the DB and server helps at all.

**Comment by YellowPhoenix18** [comment]
Well, the issue here is not SmoothTimber itself, its CoreProtect beeing slowly, basically they should do something in their log. Its not our todo to handle timeouts of different plugins like CoreProtect. That should definitely be done on their side, as they have also more infos for the reasons. May open a ticket and report that to them

**Comment by Lauriichan** [comment]
@YellowPhoenix18 I think they understood that already, what they are asking about is a debug option to log such behavior.

I think their suggestion is absolutely correct and I'll try to implement that in v2 as debug information is always useful even if u're not a developer.
Logging something like: "SmoothTimber failed to retrieve Block information from CoreProtect in x seconds" is more than enough and should tell the user or developer that CoreProtect is too slow to handle SmoothTimber's requests
