### ISSUE TITLE
ERROR IN CONSOLE - AsyncPlayerTreeFallEvent

### ISSUE THREAD

**Issue by Hazugg** [SourceWriters/SmoothTimber#13]
Error in Console

It reproduces when cutting wood of any type, trees, etc.

![image](https://user-images.githubusercontent.com/31551514/123814986-bd384e80-d8bb-11eb-83c0-079f2e633941.png)

 - Software: Paper
 - Server Version: 1.17
 - Plugin Version: 1.17.1
 - Java Version: 16

**Comment by Lauriichan** [comment]
duplicate of #12
