### ISSUE TITLE
[FEATURE] Include leaves in tree felling

### ISSUE THREAD

**Issue by michaelbmorris** [SourceWriters/SmoothTimber#17]
**Is your feature request related to a problem? Please describe.**
It feels odd to chop down a whole tree and have leaves still floating in the air. The leaves often catch the falling logs so I have to break them manually (usually requires building a scaffold to reach the leaves) or wait for them to decay before moving on. This detracts from the "smoothness" of SmoothTimber.

**Describe the solution you'd like**
I think it would be ideal for leaves to break automatically when the tree is felled. They would instantly drop saplings, sticks, apples, etc. and would not prevent logs from falling all the way to the ground.

I have a license for RealisticWorldGenerator and while I love the custom trees, they often leave behind a few fences or logs when I use this plugin. Including leaves in the felling animation would make it easier to notice the straggler wood blocks.

**Describe alternatives you've considered**
A potential alternative would be to alter how logs drop so that they don't get caught in the leaves. This would still require the player to wait around to get saplings, sticks, apples, etc. but would instantly give them the logs. I'm honestly not sure how this could be done while keeping the smooth animation.

**Additional context**
Inspiration for this feature could be drawn from mcMMO's Tree Feller skill. It breaks logs and leaves, but not fences. That makes it incompatible with RWG, which I am fond of. It also doesn't have the smooth animation.

**Comment by Oxina** [comment]
This could be solved by adding an "inclusion" configuration the same way the "exclusion" exist.
So anyone can add the blocks (material) he want like leaves.
I would like to see leaves in the blocks too, but maybe not by default.
It should be an option and I think it could be the best and easiest way to do it.

**Comment by queengooborg** [comment]
An inclusion/exclusion list is a great feature, and I'm glad to see it added!  Personally, I would love to see a simpler on/off option for leaves, something like:

```yml
options:
  leaves: true
```

**Comment by Lauriichan** [comment]
This is not something that is really possible without breaking the whole plugin.
If we add something like that and add the materials automatically people expect that it is fully supported and stuff which we can't do with our current method of detecting wood.
We just search for the whitelisted materials in a radius, now add leaves which are much more likely to connect with other trees and there you go the plugin takes ages to compute all blocks or won't even break any tree at all.

**Comment by queengooborg** [comment]
I actually just tried adding the leaves into the inclusion list, and ended up picking up a bunch of leaf blocks, rather than sticks and sapplings.  Perhaps rather than dropping the block itself, the plugin could "break" the block instead?*

I switched to this plugin after using the [TreeCapitator datapack](https://www.planetminecraft.com/data-pack/treecapitator-datapack-1-13/) (trying to use datapacks on a multi-world server is a huge pain), and it had a fairly decent leaf-breaking algorithm.  Maybe something to look into?

* Note: I'm a developer, but not one that creates Minecraft mods/plugins.  Please forgive me if something I suggest isn't so easy to implement!

**Comment by Lauriichan** [comment]
Well SmoothTimber was never intended to break leaves in the first place therefore the algorithm just drops the block as it would be wood, the only thing that the inclusion list did is well, add materials as whitelisted

**Comment by queengooborg** [comment]
If a user were to write pull requests to implement the aforementioned tweaks, would you guys be interested in it?

**Comment by Lauriichan** [comment]
I mean if someone wants to that yeah but wouldn't last long because of the current rewrite
