### ISSUE TITLE
[BUG] Tab complete shows wrong completion on 1.18 Paper

### ISSUE THREAD

**Issue by Lauriichan** [SourceWriters/SmoothTimber#20]
**Describe the bug**

Tab complete doesn't work correctly on 1.18 and shows the wrong completion

**To Reproduce**

1. Type a /smoothtimber command
2. Look at the tab complete while writing it normally

**Expected behavior**

It should shows the correct completion depending on the sub command

**Media**

![image](https://user-images.githubusercontent.com/41839265/144273307-94b613f9-ebb6-4bd4-9f92-79d53bcfec6c.png)
![image](https://user-images.githubusercontent.com/41839265/144273324-8522f48e-0b37-4315-a4c1-a78ce44c512e.png)

**Server:**

 - Software: Paper
 - Server Version: 1.18
 - Plugin Version: 1.18.0
 - Java Version: 17

**Comment by PierreSchwang** [comment]
Relates to https://github.com/PaperMC/Paper/issues/6936#issuecomment-979713795 (https://bugs.openjdk.java.net/browse/JDK-8274349)

**Comment by PierreSchwang** [comment]
The flag provided in the issue does not solve the problem, so maybe that's another issue, dk

**Comment by Lauriichan** [comment]
Wrong issue xD

**Comment by Lauriichan** [comment]
Is this fixed already?
