### ISSUE TITLE
[FEATURE] EcoSkills Support

### ISSUE THREAD

**Issue by didkoti** [SourceWriters/SmoothTimber#28]
**Is your feature request related to a problem? Please describe.**
Players don't get any Skill XP when they cut trees.

**Describe the solution you'd like**
Support for EcoSkills's woodcutting skill.

**Describe alternatives you've considered**
Asking another plugin dev to add support.

**Additional context**
EcoSkills Spigot: https://www.spigotmc.org/resources/95541/
EcoSkills GitHub: https://github.com/Auxilor/EcoSkills

**Comment by Lauriichan** [comment]
Wrong format, you're asking for plugin compat not a feature.
