### ISSUE TITLE
[FEATURE] Supporting nether warped "trees" and mushrooms

### ISSUE THREAD

**Issue by SleepyCatten** [SourceWriters/SmoothTimber#35]
**Is your feature request related to a problem? Please describe.**
Not a problem as such. I just wish that the plugin worked for all tree-like structures.

**Describe the solution you'd like**
Add support for the warped nether "trees" and all mushrooms.

**Describe alternatives you've considered**
Using a different plugin.

**Additional context**
This is done by UltimateTimber, but I don't want to use this plugin if I can avoid it.

**Comment by Lauriichan** [comment]
SmoothTimber works with the nether trees
However the Mushrooms are not considered a tree in our opinion.
If you want to you can use the inclusion feature which was newly added in 1.19.0 to add your mushroom blocks.
