### ISSUE TITLE
[BUG] JobsReborn dosn't give you money from breaking wood

### ISSUE THREAD

**Issue by Noikz** [SourceWriters/SmoothTimber#37]
**Describe the bug**
JobsReborn dosn't give money when breaking wood

**To Reproduce**
1. Mine wood logs

**Expected behavior**
Give you money

**Server:**
 - Software: [Paper]
 - Server Version: [1.18.1]
 - Plugin Version: [1.19.0]
 - Java Version: [17]

**Comment by Lauriichan** [comment]
Did you configure SmoothTimber for JobsReborn?

**Comment by Noikz** [comment]
> Did you configure SmoothTimber for JobsReborn?

from what i can see everything is set to "true"

**Comment by Lauriichan** [comment]
So you didn't configure the Jobs.yml of SmoothTimber?

**Comment by Lauriichan** [comment]
Since no answer is coming I assume this issue is solved
