### ISSUE TITLE
[COMPAT] Add compatibility for 1.18.2

### ISSUE THREAD

**Issue by nuage00** [SourceWriters/SmoothTimber#39]
**What version and plugin do you want us to add compatibility for?**

- Software: [e.g. Spigot / any] any
- Minecraft Version: [e.g. 1.16.5] 1.18.2
- Plugin: [e.g. CoreProtect] any
- Plugin Version: [e.g. 1.0 / any] any

**Why should we add compatibility for this plugin with that version?**
Because it's the latest version of Minecraft.

**Comment by Lauriichan** [comment]
Wrong issue type, this has nothing to do with third party plugin compatibility.
