### ISSUE TITLE
The plugin is knocking trees that are only connected by leaves. 

### ISSUE THREAD

**Issue by cedral** [SourceWriters/SmoothTimber#4]
how to limit it to only knock down all of things that are connected via wood?

**Comment by Lauriichen** [comment]
So the plugin is only breaking logs and fences, not leaves and its detection has nothing to do with leaves.
So if you've BlockyLog installed it doesn't break player placed blocks and maybe that's your issue here.

**Comment by cedral** [comment]
[Chopped one treeblock](https://cdn.discordapp.com/attachments/581267014543212566/698958303962857582/2020-04-12_13.51.07.png)
