### ISSUE TITLE
[HELP] Help needed

### ISSUE THREAD

**Issue by Vzlomshik1999** [SourceWriters/SmoothTimber#40]
Cuts down two trees at once, if they are nearby. How to fix it? Please help me, I cut down a tree and a house that was nearby

**Server:**

 - Software: [e.g. Paper]
 - Server Version: [e.g. 1.18.1]
 - Plugin Version: 1.21.0

**Comment by Lauriichan** [comment]
Install for example LogBlock or CoreProtect
SmoothTimber integrates into them to prevent to break player placed blocks.
However it will only work on blocks that are placed after one of these plugins was installed.

If you don't think that this is an option then you can't really fully prevent it however you can make it more safe for you or your players by for example only enabling the cutter when sneaking or that people need to enable it
