### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by HXJ08** [SourceWriters/SmoothTimber#42]
I am using paper 1.18.1 and the smoothtimber.limit.<BLOCK_AMOUNT> permission didn't work, If I set it to a number with luckperms. when i try to cut wood, it will just cancel the event and do nothing.

**Comment by Lauriichan** [comment]
Can you show me what you put into luckperms?
(The permission text)

**Comment by Lauriichan** [comment]
Please actually use the format we provide.
Its not just for fun there.
