### ISSUE TITLE
[HELP]: Config [1.19]

### ISSUE THREAD

**Issue by Anldernx** [SourceWriters/SmoothTimber#46]
### Describe what happend

I tryed to modify the config file but nothing happenend
For example: I had made it so you could toggle it at will but when i tryed it in-game it doesnt applyed
Even after a Server Restart same problem

### Reproduction steps

1. modify the config file
2. try it in-game

### Expected behavior

that you can use the command /sm toggle

### Java Version

Java 17

### Server Software

Spigot

### Minecraft Version

1.19.1

### Plugin Version

1.22.1

**Comment by Lauriichan** [comment]
Can you show me how you changed the config?

**Comment by Anldernx** [comment]
Here hope it helps

**Comment by Anldernx** [comment]
Hope it helps
Video: https://youtu.be/73xWRM_CYBA

**Comment by Lauriichan** [comment]
toggleable: 'true' doesn't exist

**Comment by Lauriichan** [comment]
Also DO NOT use /reload
SmoothTimber automatically reloads its config
And using /reload in general can and probably will break stuff

**Comment by Lauriichan** [comment]
https://confluence.syntaxphoenix.com/display/SMTIM/config.yml#config.yml-Options
See here for more info
