### ISSUE TITLE
[HELP]: Maven repo?

### ISSUE THREAD

**Issue by SkytAsul** [SourceWriters/SmoothTimber#49]
### With what do you need help?

Is there a maven repository available?
I would like to add an integration with SmoothTimber in my plugin.

**Comment by Lauriichan** [comment]
Currently SmoothTimber is not available as a maven module, at least not officially
You could try using JitPack if that builds it but as of now the SmoothTimber api of the legacy branch consists of only 3 events:

1. AsyncPlayerChopTreeEvent
  => Is called before the tree is broken which is cancellable
2. AsyncPlayerChoppedTreeEvent
  => Is called directly after the Chop event and is almost the same but not cancellable
3. AsyncPlayerTreeFallEvent
  => Is called after the tree is fully chopped and all blocks are known and stuff like that also not cancellable

Therefore I see no reason to publish it to a maven repository
The currently worked on version will definitely be released on the Github Package Registry or an other maven repository but the legacy one is mostly just the plugin

**Comment by SkytAsul** [comment]
Well, the jitpack build is failed...

**Comment by Lauriichan** [comment]
Well then simply just get the plugin jar and use it as system dependency

That's how we had to do it with a lot of plugins as well

**Comment by SkytAsul** [comment]
That's what I am doing for lot of other plugins, that's just so annoying.
There are free CI servers available which provides maven repository access, such as codemc.

**Comment by Lauriichan** [comment]
Well I guess in that case your question is answered

We will not publish the "legacy" branch as maven artifact, the "current" branch will receive multiple maven artifacts as it is completely differently structured and not just a whole plugin how the "legacy" branch is, as I said legacy has just 3 events which doesn't really make sense to publish as a api artifact.

**Comment by SkytAsul** [comment]
Alright then, thanks for answering. Any ETA for the rework to be released?

**Comment by Lauriichan** [comment]
No, there isn't.

In general we don't give any estimates
