### ISSUE TITLE
一个BUG问题，在1.12.2上出现了

### ISSUE THREAD

**Issue by BingZi-233** [SourceWriters/SmoothTimber#5]
# 在砍树的时候发生了这个问题
> 物品不在掉落
> 动画正常播放

![JKl3Nt.png](https://s1.ax1x.com/2020/04/19/JKl3Nt.png)
![JKl1AI.png](https://s1.ax1x.com/2020/04/19/JKl1AI.png)

**Comment by BingZi-233** [comment]
# 我在尝试这样修改
[![JK8Y36.png](https://s1.ax1x.com/2020/04/19/JK8Y36.png)](https://imgchr.com/i/JK8Y36)

**Comment by Lauriichen** [comment]
Okay I will check that problem out, so you are just cutting a tree on 1.12.2 right?
And the way you modified this is not compatible with every Minecraft Version.

**Comment by Lauriichen** [comment]
So what did you do to cause this?
Because I can't reproduce that bug.

**Comment by BingZi-233** [comment]
您可以来到我的服务器进行复现
fwq.iceyun.net:234

**Comment by Lauriichen** [comment]
So what do I've to type at /register
Because I can't read Chinese, I'm using a translator for that xD

**Comment by Lauriichen** [comment]
okay now it worked suprisingly xD

**Comment by BingZi-233** [comment]
请按下F键，选择中间的按钮，在选择左上角的第一个树苗

**Comment by BingZi-233** [comment]
服务器用了一些伪英语，您可以猜一下大致什么意思

**Comment by Lauriichen** [comment]
okay
So my main problem is I've no idea where I should click xD

**Comment by BingZi-233** [comment]
后台好像操控起来很难，我尽量进行尝试

**Comment by Lauriichen** [comment]
I'm not able to connect again, my ping is too high
(I had a ping of ~2700ms)

**Comment by Lauriichen** [comment]
So the problem is that the item is null but I've no idea how this is possible at all, so what type of block are you trying to break?

**Comment by BingZi-233** [comment]
由地图生成的树木，我放置下来的就可以被正常的落下

**Comment by Lauriichen** [comment]
Ohhh
I know the problem, I will fix it in a second

**Comment by BingZi-233** [comment]
谢谢

**Comment by Lauriichen** [comment]
I think the problem is that fences aren't built into the one method here

**Comment by Lauriichen** [comment]
![image](https://user-images.githubusercontent.com/41839265/79689254-c78ca080-8253-11ea-9d04-799e825ec97c.png)

**Comment by Lauriichen** [comment]
Btw if you ever need an good translator use https://www.deepl.com/ it's awesome

**Comment by BingZi-233** [comment]
emm，可能是因为这个问题

**Comment by BingZi-233** [comment]
可以返回一个日志，让管理员知道是什么问题

**Comment by Lauriichen** [comment]
uh okay

**Comment by BingZi-233** [comment]
我应该给您提供一个完整的进入流程，可是我正在进行 PUBG 没有办法切换出去给您截图
很抱歉

**Comment by Lauriichen** [comment]
It's okay xD
Play your match xD

**Comment by Lauriichen** [comment]
Also I think I will not need a log or something uhm yeah
So what I wanted to say is that the update I'm pushing now, so the newest commit should not be built because there are still work in progress features inbuilt

**Comment by BingZi-233** [comment]
漏洞的修复的确应该被归类到当前进行的版本，而不是重新发布一个新的版本

**Comment by BingZi-233** [comment]
我尝试了重新构建，通过
`Material material = block.getBlockData().getMaterial();
		MaterialData materialData = new MaterialData(material);`
的方式不在获取null，但是我失败了

**Comment by Lauriichen** [comment]
So the fix I made wasn't working or what?

**Comment by Lauriichen** [comment]
Wait I forgot to push it xD

**Comment by Lauriichen** [comment]
Okay commited and pushed it now

**Comment by BingZi-233** [comment]
感谢

**Comment by BingZi-233** [comment]
Spigot上并没有新的构建产生，是否是需要下一个版本？

**Comment by Lauriichen** [comment]
Huh as far as I know there shouldn't why are you asking?
