### ISSUE TITLE
[BUG] Large jungle tree leaves and vines don't decay

### ISSUE THREAD

**Issue by CrispyDairy** [SourceWriters/SmoothTimber#5]
**Describe the bug**

When chopping down a jungle tree with the plugin, it's leaves don't start decaying. Also the vines stay. This is probably an issue with them not updating that the wood is gone.
**To Reproduce**

**Expected behavior**

The vines and leaves should decay like any other.
**Media**

![image](https://user-images.githubusercontent.com/81482501/119997574-862efe80-bfd8-11eb-8d03-07448a6927ba.png)

**Server:**

 - Software: Regular paper
 - Server Version: 1.16.5
 - Plugin Version: 1.6.1 I believe.

**Additional context**

**Comment by PierreSchwang** [comment]
Are you sure that no logs are remaining inside the leaves?

**Comment by CrispyDairy** [comment]
I'm sure, I broke some of the leaves myself to check

**Comment by Lauriichan** [comment]
So my guess is that this is an issue of Paper and not SmoothTimber

======

I just tried it myself and it just worked fine, all leaves decayed.
And as those decayed the vines were removed as well, this seems to be a issue of another third-party plugin that you maybe got installed or Paper itself (I always test on spigot)
