### ISSUE TITLE
[BUG]:the ground gets removed 

### ISSUE THREAD

**Issue by aarron1993** [SourceWriters/SmoothTimber#50]
### Describe what happend

when i use the plugin it removes the ground below the tree not the tree.
playing on paper 1.19.2 

it has worked before on there but not now 

thanks for all your hard work 

### Reproduction steps

plant a tree/or any tree
hit the tree with a stone axe 

### Expected behavior

to cut down the tree all of it like before 

### Media

![image](https://user-images.githubusercontent.com/103454117/199132625-b11e6515-64b7-4ff7-bcdc-320552c64174.png)

### Java Version

Java 17

### Server Software

paper

### Minecraft Version

1.19.2

### Plugin Version

1.22.3

### Additional Information

thank you

**Comment by Lauriichan** [comment]
Downgrade to 1.22.2 for now
We already know about this bug and will fix it soon
It is only releated to mc 1.13+

**Comment by Lauriichan** [comment]
Fixed in 88ea9777d2ed62a9df0b50b65b059078644b8d96
