### ISSUE TITLE
[BUG]:not only breaking trees

### ISSUE THREAD

**Issue by VulcanoSoftware** [SourceWriters/SmoothTimber#54]
### Describe what happend

ok so this plugin isn't only breaking trees but also wood houses, my player was building a house and broke accidentaly a log with his axe, then his wole house got destroyed.

### Reproduction steps

1. my friend was building his house
2. he broke a wooden log in his house
3. his wole house got destroyed

### Expected behavior

can you maybe make a tree recognition system so only trees got broken?

### Java Version

Java 18

### Server Software

purpur

### Minecraft Version

1.19.3

### Plugin Version

1.22.5

**Comment by YellowPhoenix18** [comment]
Related to #53 , please read also old issues before opening a new one
