### ISSUE TITLE
[HELP]: What does "at one time" mean in limit?

### ISSUE THREAD

**Issue by VaibhavSys** [SourceWriters/SmoothTimber#63]
### With what do you need help?

In the [wiki](https://confluence.syntaxphoenix.com/display/SMTIM/config.yml), in the limit section it says "Specifies the default amount of blocks that a player without special permissions can break **at one time."**
I am not sure what **at one time** means here, does it mean in one session (player logs into server then logs out) or what does it mean?

### Java Version

Java 17

### Server Software

Purpur

### Minecraft Version

1.19.4

**Comment by Lauriichan** [comment]
At one time simply means once you start cutting the tree. This cutting process is the "one time" it refers to

**Comment by VaibhavSys** [comment]
> At one time simply means once you start cutting the tree. This cutting process is the "one time" it refers to

So the "one time" resets after I am done cutting that tree? So it will reset for each tree?
If I set one time limit to 5, a player can only cut 5 blocks of log from each tree using smooth timber?

**Comment by Lauriichan** [comment]
Exactly, I don't know if it will only break 5 blocks or if it cancels the cutting process anymore

**Comment by VaibhavSys** [comment]
> Exactly, I don't know if it will only break 5 blocks or if it cancels the cutting process anymore

Alright, thanks!
