### ISSUE TITLE
[HELP]: Plugin not working

### ISSUE THREAD

**Issue by Robo5626** [SourceWriters/SmoothTimber#65]
### With what do you need help?

i added it to my server but it isnt working is there because i can use the commands but when i enable it the trees dont fall and i dont know what i di dwrong 

### Java Version

Java 17

### Server Software

paper

### Minecraft Version

1.20

**Comment by Lauriichan** [comment]
Could you provide a full server log?

EDIT: As well as your config.yml

**Comment by Surax23** [comment]
I can.
```
purpur-1.20.1-2004
Java 17
SmoothTimber 1.24.5
```
config.yml: https://pastebin.com/1x81QFvw
latest.log: https://pastebin.com/rED2qyrP

All the same problem.

**Comment by Lauriichan** [comment]
Sorry I couldn't check the log in time, I didn't notice that you replied here.
But from what I was able to see from your config file it seems like you
1. Have to toggle on the tool begore you can use it
2. You have to sneak to use it

I can't help more without a log or the info what "addon plugins" are installed.

**Comment by Lauriichan** [comment]
I'm guessing that this was resolved because I didn't get any answer anymore - closing issue
