### ISSUE TITLE
[REVISION]: Update all of dependencies

### ISSUE THREAD

**Issue by NoltoxGit** [SourceWriters/SmoothTimber#75]
### Is your feature request related to a problem? Please describe.

Would it be possible to update the various plugin dependencies please?

### Describe the solution you'd like

Update all of dependencies of the plugin. 

### Specify the classes and lines which would be affected

The `pom.xml` and `SmoothTimber/tree/legacy/libraries` would have to be modified.

**Comment by Lauriichan** [comment]
We already know that there was an update of Lands and the dev that is supposed to do it didn't have the time to work on it yet.
We also can't just update the dependency as SmoothTimber supports many different versions and therefore needs to support multiple plugin versions of each plugin.

**Comment by Lauriichan** [comment]
Could u please not close issues on your own, that would be helpful.

**Comment by Lauriichan** [comment]
@SyntaxJason was advised to work on this once he got time so it should atleast be added until the end of the year.

**Comment by Lauriichan** [comment]
Updated plugins in f4f5ae8e334561217ec87f741108961ea0e20b36
