### ISSUE TITLE
[BUG]:It doesn't work on the Spigot(Paper) server of version 1.20.4

### ISSUE THREAD

**Issue by hiyakake** [SourceWriters/SmoothTimber#77]
### Describe what happend

The plug-in worked fine until 1.20.2 of Spigot, but it does not work on 1.20.3 and 1.20.4.

### Reproduction steps

1. Add a plug-in file to Spigot
2. Log in and cut a tree.
3. It doesn't work

### Expected behavior

a

### Java Version

Java 17

### Server Software

paper

### Minecraft Version

1.20.4

### Plugin Version

1.24.7

**Comment by Lauriichan** [comment]
Wrong type of issue but its fine, yeah support for those versions were not added yet

**Comment by Lauriichan** [comment]
Was add in da7b9c3
