### ISSUE TITLE
mcmmo[HELP]:

### ISSUE THREAD

**Issue by Flearl** [SourceWriters/SmoothTimber#83]
### With what do you need help?

I have a problem with mcmmo and dont know why
![Problem](https://github.com/SourceWriters/SmoothTimber/assets/76784067/72904055-1c10-4202-b205-f4f4e6de5f0d)

### Java Version

Java 8

### Server Software

paper

### Minecraft Version

1.20.4

**Comment by Lauriichan** [comment]
I don't think this should be a help issue

**Comment by Lauriichan** [comment]
Could you please create a "Plugin compatibility request", that would be amazing, I can't really help without the required information
