### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by fortunatas1** [SourceWriters/SmoothTimber#85]
### Describe what happend

https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/2068#issuecomment-2089137004

### Reproduction steps

https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/2068#issuecomment-2089137004

### Expected behavior

https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/2068#issuecomment-2089137004

### Java Version

Java 18

### Server Software

Purpur

### Minecraft Version

1.20.1

### Plugin Version

Latest

**Comment by Lauriichan** [comment]
Not a bug
