### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [SourceWriters/SmoothTimber#90]
### With what do you need help?

Does this plugin have discord?

### Java Version

Java 8

### Server Software

Bukkit

### Minecraft Version

1.16.1

**Comment by YellowPhoenix18** [comment]
Read the documentation there is a discord button

**Comment by Fireworkstars46** [comment]
Don't see it

**Comment by YellowPhoenix18** [comment]
> Don't see it

On top of the page as image with written Discord

**Comment by Fireworkstars46** [comment]
![image](https://github.com/SourceWriters/SmoothTimber/assets/30112538/7ff4a2a3-35d0-41c0-a792-9bbe85d694ee)

**Comment by YellowPhoenix18** [comment]
> ![image](https://private-user-images.githubusercontent.com/30112538/337989831-7ff4a2a3-35d0-41c0-a792-9bbe85d694ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTg1NzgsIm5iZiI6MTcxNzk1ODI3OCwicGF0aCI6Ii8zMDExMjUzOC8zMzc5ODk4MzEtN2ZmNGEyYTMtMzVkMC00MWMwLWE3OTItOWJiZTg1ZDY5NGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE4Mzc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYmE2MTg1MThkYThhYTgzNTIwZWZmYzRjNTI2MjllNTc2ODg3MDM2YWRhNzEyMGZkZTNkZDVjODI0ZjBhOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mZki8muRm01sDWvBQyMTmCcbKD1SSzof3aG6PpPZrJc)

I mean the spigot-page. This is just the github-repository. The official download and latest release is provided via spigotmc.org
