### ISSUE TITLE
[HELP]:Player planted sapling on coreprotect

### ISSUE THREAD

**Issue by tritri301** [SourceWriters/SmoothTimber#94]
### With what do you need help?

Hi, I own a server and installed smoothtimber, but seems like with coreprotect, smoothtimber detects player planted trees as a house. It stems from the fact that coreprotect tags player planted trees as if they had built the thing, is there any ways that you know of to get around the issue?

Thanks!

### Java Version

Java 17

### Server Software

paper

### Minecraft Version

1.20.1

**Comment by Lauriichan** [comment]
This should not happen, could u please provide both the version of CoreProtect and SmoothTimber that you are using?
Maybe even a full server log?

**Comment by Lauriichan** [comment]
Also can you inspect a block that has such an issue and show the result here?

**Comment by tritri301** [comment]
Ok, so i'm closing this. Found out my coreprotect plugin wasn't up to date, and upgrading it fixed the issue :)
